services:
  - type: web
    name: addictiontube-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
      - key: PINECONE_API_KEY
